# Gangs Plugin Configuration

# Database Configuration
database:
  # Database type: mysql or sqlite
  type: sqlite
  
  # SQLite Configuration (used when type is sqlite)
  sqlite:
    file: "gangs.db" # Database file path (relative to plugin folder)
  
  # MySQL Configuration (used when type is mysql)
  mysql:
    host: localhost
    port: 3306
    database: gangs
    username: gangs_user
    password: "secret" # Use quotes if your password contains special characters
    pool-size: 10 # Recommended: 10

# Gang Settings
gang:
  name:
    min-length: 3
    max-length: 16
    # Regex for allowed characters (default: alphanumeric)
    allowed-characters: "^[a-zA-Z0-9]+$"
  description:
    max-length: 24
  # Time in seconds before a pending gang invite expires. Default: 3600 (1 hour)
  invites:
    expiry-seconds: 3600

# Gang List Command Settings
list:
  items-per-page: 10

# Default value returned by %gang_name% when a player is not in a gang.
no-gang-value: "None"

# Default value for no gang (used in placeholders, etc.)
default-no-gang-value: "None"