name: Gangs
version: 1.0.0
bootstrapper: com.ashank.gangs.GangsPluginBootstrap
main: com.ashank.gangs.GangsPlugin
api-version: '1.21'
author: Ashank 
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true 